# Generated by Django 3.2.14 on 2022-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_routine_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='exercise_image',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='method',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='status',
        ),
        migrations.AlterField(
            model_name='routine',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
