# Generated by Django 3.2.14 on 2022-07-17 09:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220715_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='picture',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
