# Generated by Django 3.2.14 on 2022-07-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-added_on']},
        ),
    ]
